services:
  - type: web
    plan: free
    name: TechMagazineAutoFilterBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/tamiaaaa/PROFESSOR-BOT      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URI
        sync: false 
      - key: LOG_CHANNEL
        sync: false
      - key: SUPPORT_CHAT
        sync: false
    autoDeploy: true
